#!/bin/sh
set -e
echo "Content-type: application/json"
echo ""

if [[ "$PATH_INFO" == "" ]]; then
  if [[ "$REQUEST_METHOD" == "GET" ]]; then
    cat rabbits.json
  elif [[ "$REQUEST_METHOD" == "POST" ]]; then
    jq ".[length] |= .+ $(cat)" rabbits.json | sponge rabbits.json
    echo '{"success":true}' | jq
  elif [[ "$REQUEST_METHOD" == "DELETE" ]]; then
    echo "[]" > rabbits.json
  fi
else 
  ID=$(echo $PATH_INFO | cut -c 2-)
  if [[ "$REQUEST_METHOD" == "GET" ]]; then
    jq ".[] | select(.id == $ID)" rabbits.json
  elif [[ "$REQUEST_METHOD" == "DELETE" ]]; then
    jq "del(.[] | select(.id == $ID))" rabbits.json | sponge rabbits.json
    echo '{"success":true}' | jq
  fi
fi
